### PR TITLE
Develop init project

### PR DESCRIPTION
**Pull request by daanloopes**
This merge request will be prepared the project to be functional correctly.

Commits:
Add README file 571de24
Add gitignore file 379073d

### CODE REVIEW

**Review by daanloopes — COMMENTED** [review]
All files was verified.

README.md
.gitignore

**Comment by daanloopes** [comment]
Delete development branch after merged to master

**Comment by daanloopeshelper** [comment]
### **All files was verified.**

1. README.md
2. .gitignore

**Review by daanloopeshelper — COMMENTED** [review]
### **All files was verified.**

### **Files:**

1. README.md
2. .gitignore

**Pull request merged**
